# Instead of generating SSL cert, prepare for managed cert
- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: "0755"

- name: Create runtime configuration script
  template:
    src: configure-runtime.sh.j2
    dest: /usr/local/bin/configure-runtime
    mode: "0755"
  vars:
    nginx_conf_template: "{{ lookup('file', 'nginx.conf.j2') }}"

# Create a systemd service to run the runtime configuration
- name: Install runtime configuration service
  template:
    src: runtime-config.service.j2
    dest: /etc/systemd/system/runtime-config.service
    mode: "0644"

- name: Enable runtime configuration service
  systemd:
    name: runtime-config
    enabled: yes
    daemon_reload: yes
