- name: Set web interface permissions
  file:
    path: /opt/gcp-ovpn-portal
    owner: www-data
    group: www-data
    recurse: yes

- name: Install web interface dependencies
  command:
    cmd: pip install gcp-ovpn-portal
    chdir: /opt/gcp-ovpn-portal
  become_user: www-data

- name: Install systemd service
  template:
    src: vpn-web.service.j2
    dest: /etc/systemd/system/vpn-web.service
    mode: "0644"

- name: Enable and start services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - vpn-web
    - openvpn@server
    - nginx
