- name: Set web interface permissions
  ansible.builtin.file:
    path: /opt/gcp-ovpn-portal
    owner: www-data
    group: www-data
    recurse: true

- name: Install web interface dependencies
  ansible.builtin.pip:
    name: gcp-ovpn-portal
    chdir: /opt/gcp-ovpn-portal
  become_user: www-data

- name: Install systemd service
  ansible.builtin.template:
    src: vpn-web.service.j2
    dest: /etc/systemd/system/vpn-web.service
    mode: "0644"

- name: Enable and start services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - vpn-web
    - openvpn@server
    - nginx
