# Instead of generating SSL cert, prepare for managed cert
- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: "0755"

- name: Create runtime configuration script
  ansible.builtin.template:
    src: configure-runtime.sh.j2
    dest: /usr/local/bin/configure-runtime
    mode: "0755"

# Create a systemd service to run the runtime configuration
- name: Install runtime configuration service
  ansible.builtin.template:
    src: runtime-config.service.j2
    dest: /etc/systemd/system/runtime-config.service
    mode: "0644"

- name: Enable runtime configuration service
  ansible.builtin.systemd:
    name: runtime-config
    enabled: true
    daemon_reload: true

# Remove the default Nginx site
- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

# Reload Nginx to apply the changes
- name: Reload Nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Install certificate renewal script
  ansible.builtin.template:
    src: templates/renew-certs.sh.j2
    dest: /usr/local/bin/renew-certs.sh
    mode: "0755"
  become: true

- name: Create a cron job for Certbot auto-renewal
  ansible.builtin.cron:
    name: "Certbot Auto-Renewal"
    job: "/usr/local/bin/renew-certs.sh"
    user: root
    state: present
    minute: 0
    hour: 0
  become: true
