- name: Install required packages
  ansible.builtin.apt:
    name:
      - openvpn
      - easy-rsa
      - nginx
      - python3-pip
      - git
      - make
      - curl
      - iptables-persistent
      - certbot
      - python3-certbot-nginx
    state: present
    install_recommends: false

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-ip-forward.conf
    reload: true
