steps:
  # Get latest version
  - name: "us-central1-docker.pkg.dev/abby-ranson/docker/github-ops-builder"
    args: ["get-version", "${_REPO_OWNER}", "${_REPO}"]
    secretEnv: ["GITHUB_TOKEN"]
    id: "get-version"

  # Process PR info and bump version
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "bump-version"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--current-version"
      - "$$(cat current_version.txt)"
      - "--version-type"
      - "${_PR_TYPE}"
      - "--is-merge"
      - "${_IS_MERGE}"
      - "--pr-number"
      - "${_PR_NUMBER}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "bump-version"
    waitFor: ["get-version"]

  # Publish to PyPI if this is a merge to main
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/dev-tools-builder:basic"
    entrypoint: "bash"
    args:
      - "-c"
      - make build IMAGE_VERSION="$$(cat new_version.txt)" GCP_PROJECT=${PROJECT_ID}
    id: "build"
    waitFor: ["bump-version"]

  # Create GitHub release
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "create-release"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-prod"
      - "${_IS_MERGE}"
      - "--skip-asset"
    secretEnv: ["GITHUB_TOKEN"]
    id: "create-release"
    waitFor: ["build"]

  # Update parent repo submodule
  - name: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/github-ops-builder"
    args:
      - "update-submodule"
      - "${_REPO_OWNER}"
      - "${_REPO}"
      - "--parent-repo"
      - "${_PARENT_REPO}"
      - "--submodule-path"
      - "${_SUBMODULE_PATH}"
      - "--current-version"
      - "$$(cat new_version.txt)"
      - "--is-merge"
      - "${_IS_MERGE}"
    secretEnv: ["GITHUB_TOKEN"]
    id: "update-submodule"
    waitFor: ["create-release"]

substitutions:
  _REPO: "ansible-openvpn"
  _LOCATION: us-central1
  _REPO_OWNER: ""
  _PR_TYPE: ""
  _IS_MERGE: "false"
  _PR_NUMBER: ""
  _PARENT_REPO: "portfolio"
  _SUBMODULE_PATH: "assets/images/ansible-openvpn" # adjust this path

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/$PROJECT_ID/serviceAccounts/cloud-builder@${PROJECT_ID}.iam.gserviceaccount.com"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: "GITHUB_TOKEN"
