- name: Configure VPN Server
  hosts: localhost
  connection: local
  become: true
  vars:
    ovpn_port: 1194

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: base
    - role: openvpn
    - role: nginx
    - role: web_interface
